In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [2]:
type(test_array[3])

numpy.float64

In [3]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [4]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [5]:
print(test_array.dtype)

float64


In [6]:
print(test_array.shape)

(4,)


In [7]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [8]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [9]:
tensor_rank3 = [
                 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], 
                 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                 [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
                ]
np.array(tensor_rank3, int).ndim

3

In [10]:
np.array(tensor_rank3, int).size

48

In [11]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [13]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize # numpy 배열에서 각 요소가 차지하는 바이트 확인

8

In [14]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [15]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [16]:
x.reshape(-1,) # 튜플 형태

array([1, 2, 5, 8, 1, 2, 5, 8])

In [17]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [19]:
x = np.array(range(8)).reshape(4, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
x.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
x = np.array(range(8)).reshape(2, 2, 2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])