In [2]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x[0]

array([1, 2, 3])

In [4]:
x[0, 2]

3

In [5]:
x[0, 1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [6]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:, 2:] # 3, 4, 5 / 8, 9, 10

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [7]:
x[1, 1:3]

array([7, 8])

In [8]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [9]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
x.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
x[::, ::]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
x[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [13]:
x[::2, ::3]

array([[ 0,  3],
       [10, 13]])

In [14]:
np.arange(10) # range 함수와 달리 증가값에 실수형이 입력되어도 값 생성 가능

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [16]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
np.ones(shape=(5, 2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [18]:
np.zeros(shape=(2, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [19]:
np.empty(shape=(2, 4), dtype=np.float32)

array([[-1.14206635e-17,  3.26544581e-41,  0.00000000e+00,
         0.00000000e+00],
       [ 7.14662217e-44,  1.30320757e-43, -1.76968608e-35,
         4.40217913e-41]], dtype=float32)

In [20]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.empty_like(x)

array([[100088364825383,               0,               0,
                      0],
       [              0,               0,               0,
                      0],
       [              0,               0,               0,
                      0]])

In [24]:
np.identity(n=4, dtype=int) # 단위행렬(i행렬)을 생성

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [25]:
np.eye(N=3, M=6) # 시작점과 행렬 크기를 지정, 단위행렬 생성

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [26]:
np.eye(N=3, M=5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [27]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.diag(matrix) # 행렬의 대각성분 값 추출

array([0, 4, 8])

In [ ]:
np.diag(matrix, k=1) # k 인자로 출발점 지정

In [33]:
np.random.uniform(0, 5, 10) # 균등 분포 함수 : 각 숫자가 나타날 확률이 동일한 값

array([0.54322165, 1.58610751, 0.8381216 , 4.53355972, 0.89853461,
       4.27511921, 2.48783637, 4.2075138 , 2.59045693, 1.37318762])

In [34]:
np.random.normal(0, 2, 10)

array([-0.65955435, -1.63414879,  0.84746176,  0.64305449, -1.12137551,
        2.68556036, -1.49741586, -3.58961185,  0.94463293, -1.67883056])

In [35]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

55

In [43]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array # Rank 2 = 행렬

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [38]:
test_array.sum(axis=1)

array([10, 26, 42])

In [39]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [40]:
third_order_tensor.shape

(3, 3, 4)

In [41]:
third_order_tensor.ndim # 랭크 0 : 스칼라, 랭크 1 : 벡터, 랭크 2 : 행렬, 랭크 3 : 텐서

3

In [44]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [45]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [46]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [47]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [ ]:
test_array.std() # 전체 값들에 대한 표준편차 연산

In [49]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [50]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [52]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.hstack((v1, v2))

array([1, 2, 3, 4, 5, 6])

In [55]:
v1 = v1.reshape(-1, 1) # v1의 기존 shape = (1, 3) -> reshape 후 (3, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [59]:
np.hstack((v1, v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1, v2), axis=0) # vstack()과 같은 기능

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate((v1, v2), axis=1) # hstack()과 같은 기능

array([[1, 2, 3, 4, 5, 6]])

In [62]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)

In [63]:
v1

array([[1, 2],
       [3, 4]])

In [65]:
v2 = np.array([[5, 6]]).T # (1, 2) -> (2, 1)

In [66]:
v2.shape

(2, 1)

In [67]:
v2

array([[5],
       [6]])

In [70]:
np.concatenate((v1, v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [71]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [73]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [74]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [81]:
x_1 = np.arange(1, 7).reshape(2, 3)
x_2 = np.arange(1, 7).reshape(2, 3)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
x_2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [82]:
x_1.dot(x_2.T)

array([[14, 32],
       [32, 77]])

In [85]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [87]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [88]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [89]:
x % 3

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [91]:
x = np.arange(1, 13).reshape(4, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [93]:
x + v # 브로드캐스팅 : 하나의 행렬과 스칼라 값들의 간의 연산이나 행렬과 벡터 간의 연산

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [94]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

In [95]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [96]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [97]:
(x>3).all()

False

In [98]:
(x>3).any()

True

In [99]:
(x<10).all()

True

In [101]:
(x<10).any()

True

In [102]:
(x>10).any()

False

In [105]:
x = np.array([4, 6, 7, 3, 2], dtype = int)
x > 5 # F T T F F

array([False,  True,  True, False, False])

In [106]:
np.where(x>5) # 1 2

(array([1, 2]),)

In [107]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5, "참", "거짓")

array(['거짓', '참', '참', '거짓', '거짓'], dtype='<U2')

In [108]:
x = np.array([4, 5, 7, 3, 2])
np.argsort(x) # 배열 내 값들을 작은 순서대로 인덱스를 반환

array([4, 3, 0, 1, 2])

In [109]:
np.argmax(x)

2

In [110]:
np.argmin(x)

4

In [111]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [113]:
cond = x > 3 # 불린 인덱스
cond

array([ True,  True,  True, False, False])

In [115]:
x[cond] # True 인덱스에 해당하는 값들이 출력됨.

array([4, 6, 7])

In [116]:
x.shape

(5,)

In [117]:
cond.shape

(5,)

In [118]:
x = np.array([9, 2, 3, 2, 0, 0, 2])
cond = np.array([1, 2, 4, 3, 0, 2, 2, 2], int) # 팬시 인덱스
x[cond] # 2, 3, 0, 2, 9, 3, 3, 3

array([2, 3, 0, 2, 9, 3, 3, 3])

In [119]:
x.take(cond)

array([2, 3, 0, 2, 9, 3, 3, 3])

In [120]:
x = np.array([[1, 4], [9, 16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a, b]

array([ 1,  9,  9, 16,  4,  4])